kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: website-controller
  namespace:
  labels:
spec:
  template:
    metadata:
      labels:
        app: website-controller
    spec:
      containers:
      - image: kalise/k8s-website-controller:0.1
        name: nodejs
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website-controller
  namespace:
  labels:
spec:
  selector:
    app: website-controller
  ports:
  - port: 80
    targetPort: 8060
