kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: website-controller
  namespace:
  labels:
spec:
  template:
    metadata:
      labels:
        app: website-controller
    spec:
      containers:
      - name: nodejs
        # use 0.2 if you have nginx as ingress controller running in your cluster
        image: kalise/k8s-website-controller:0.2
        # use 0.1 if you have traefik as ingress controller running in your cluster
        #image: kalise/k8s-website-controller:0.1
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website-controller
  namespace:
  labels:
spec:
  selector:
    app: website-controller
  ports:
  - port: 80
    targetPort: 8060
