---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: meta-controller
  namespace: meta-controller
  labels:
    app: meta-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta-controller
  serviceName: ""
  template:
    metadata:
      labels:
        app: meta-controller
    spec:
      serviceAccountName: meta-controller
      containers:
      - name: meta-controller
        image: metacontroller/metacontroller:0.2
        command: ["/usr/bin/metacontroller"]
        args:
        - --logtostderr
        - -v=8
        - --discovery-interval=20s
