---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: meta-controller
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: meta-controller
subjects:
- kind: ServiceAccount
  name: meta-controller
  namespace: meta-controller
roleRef:
  kind: ClusterRole
  name: meta-controller
  apiGroup: rbac.authorization.k8s.io
