---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webctl
  labels:
    app: webctl
  namespace: meta-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webctl
  template:
    metadata:
      labels:
        app: webctl
    spec:
      restartPolicy: Always
      containers:
      - name: webhook
        image: kalise/webctl:latest
        resources:
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: webctl
  namespace: meta-controller
  labels:
    app: webctl
spec:
  selector:
    app: webctl
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: webctl
spec:
  generateSelector: true
  resyncPeriodSeconds: 10
  parentResource:
    apiVersion: applications.clastix.io/v1
    resource: websites
  childResources:
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: Recreate
  - apiVersion: extensions/v1beta1
    resource: ingresses
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://webctl